Repository fluxcd/flagger, pull requests merged in 2021-09, with the labels that each got.

#1012 Add Influxdb metric provider
  docs/gitbook/usage/metrics.md
  go.mod
  go.sum
  pkg/metrics/providers/factory.go
  pkg/metrics/providers/influxdb.go
  pkg/metrics/providers/influxdb_test.go
  pkg/metrics/providers/stackdriver.go
  pkg/metrics/providers/stackdriver_test.go
Labels: kind/feature

#1018 [docs] update promql query for istio request duration
  docs/gitbook/faq.md
Labels: kind/docs

#1025 Update Gloo to 1.9.0
  test/gloo/install.sh
Labels: kind/build
