Repository fluxcd/flagger, pull requests merged in 2021-05, with the labels that each got.

#916 e2e: Update Istio and Contour
  test/contour/install.sh
  test/istio/install.sh
Labels: kind/build

#914 ConfigTracker: Scan envFrom in init-containers
  pkg/canary/config_tracker.go
  pkg/canary/config_tracker_test.go
  pkg/canary/daemonset_fixture_test.go
  pkg/canary/deployment_fixture_test.go
Labels: kind/enhancement

#915 Add Graphite metrics provider
  artifacts/flagger/crd.yaml
  charts/flagger/crds/crd.yaml
  docs/gitbook/usage/metrics.md
  kustomize/base/flagger/crd.yaml
  pkg/metrics/providers/factory.go
  pkg/metrics/providers/graphite.go
  pkg/metrics/providers/graphite_test.go
Labels: kind/feature

#922 Improve the Flagger documentation
  docs/gitbook/README.md
  docs/gitbook/dev/dev-guide.md
  docs/gitbook/faq.md
Labels: kind/docs
