Repository fluxcd/flagger, pull requests merged in 2021-03, with the labels that each got.

#843 docs: update resources to disable mTLS in Istio
  docs/gitbook/faq.md
Labels: kind/docs

#846 e2e fix: Update Contour installer
  test/contour/install.sh
  test/gloo/install.sh
Labels: kind/build

#857 Update Kubernetes packages to v1.20.4
  .github/workflows/codeql-analysis.yml
  .github/workflows/fossa.yml
  .github/workflows/scan.yml
  Dockerfile
  go.mod
  go.sum
Labels: kind/build

#859 feat: added WaitingPromotion phase
  artifacts/flagger/crd.yaml
  charts/flagger/crds/crd.yaml
  docs/gitbook/usage/how-it-works.md
  kustomize/base/flagger/crd.yaml
  pkg/apis/flagger/v1beta1/status.go
  pkg/canary/status.go
  pkg/controller/scheduler.go
  pkg/controller/scheduler_hooks.go
Labels: kind/feature
