Repository fluxcd/flagger, pull requests merged in 2022-06, with the labels that each got.

#1212 e2e: Update providers and Kubernetes to v1.23
  .github/workflows/e2e.yaml
  test/contour/install.sh
  test/gatewayapi/install.sh
  test/gatewayapi/test-ab.sh
  test/gatewayapi/test-bg.sh
  test/gatewayapi/test-canary.sh
  test/gloo/install.sh
  test/istio/install.sh
  test/kuma/install.sh
  test/linkerd/install.sh
  test/nginx/install.sh
  test/osm/install.sh
  test/skipper/install.sh
  test/skipper/kustomization.yaml
  test/traefik/install.sh
Labels: kind/build

#1211 Introduce `ScalerReconciler` and refactor HPA reconciliation
  pkg/canary/deployment_controller.go
  pkg/canary/deployment_controller_test.go
  pkg/canary/deployment_fixture_test.go
  pkg/canary/factory.go
  pkg/canary/hpa_reconciler.go
  pkg/canary/hpa_reconciler_test.go
  pkg/canary/scaler_reconciler.go
  pkg/canary/scaler_reconciler_fixture_test.go
  pkg/controller/scheduler.go
  test/kubernetes/run.sh
  test/kubernetes/test-hpa.sh
Labels: kind/enhancement

#1215 Fix primary HPA label reconciliation
  pkg/canary/hpa_reconciler.go
  pkg/canary/hpa_reconciler_test.go
Labels: kind/bug

#1220 typo: boostrap -> bootstrap
  docs/gitbook/tutorials/appmesh-progressive-delivery.md
  docs/gitbook/tutorials/contour-progressive-delivery.md
  docs/gitbook/tutorials/kuma-progressive-delivery.md
  docs/gitbook/tutorials/linkerd-progressive-delivery.md
  docs/gitbook/tutorials/osm-progressive-delivery.md
Labels: kind/docs

#1221 typo: controller
  docs/gitbook/usage/metrics.md
Labels: kind/docs
