Repository fluxcd/flagger, pull requests merged in 2022-11, with the labels that each got.

#1306 Fix cluster name inclusion in alerts metadata
  pkg/controller/events.go
Labels: kind/bug

#1280 Add support for session affinity during weighted routing with Istio
  artifacts/flagger/crd.yaml
  charts/flagger/crds/crd.yaml
  docs/gitbook/tutorials/istio-progressive-delivery.md
  docs/gitbook/usage/deployment-strategies.md
  kustomize/base/flagger/crd.yaml
  pkg/apis/flagger/v1beta1/canary.go
  pkg/apis/flagger/v1beta1/status.go
  pkg/apis/flagger/v1beta1/zz_generated.deepcopy.go
  pkg/apis/istio/v1alpha3/virtual_service.go
  pkg/apis/istio/v1alpha3/zz_generated.deepcopy.go
  pkg/router/istio.go
  pkg/router/istio_test.go
Labels: kind/enhancement

#1321 update gateway api docs to v1beta1
  docs/gitbook/tutorials/gatewayapi-progressive-delivery.md
Labels: kind/docs
