Repository fluxcd/flagger, pull requests merged in 2022-01, with the labels that each got.

#1085 Add kuma support for progressive traffic shifting canaries
  .gitbook.yaml
  .github/workflows/e2e.yaml
  artifacts/examples/kuma-canary.yaml
  charts/flagger/templates/rbac.yaml
  cmd/flagger/main.go
  docs/diagrams/flagger-kuma-canary.png
  docs/gitbook/README.md
  docs/gitbook/SUMMARY.md
  docs/gitbook/tutorials/kuma-progressive-delivery.md
  docs/gitbook/usage/deployment-strategies.md
  hack/update-codegen.sh
  kustomize/base/flagger/rbac.yaml
  kustomize/kuma/kustomization.yaml
  kustomize/kuma/patch.yaml
  pkg/apis/flagger/v1beta1/provider.go
  pkg/apis/kuma/register.go
  pkg/apis/kuma/v1alpha1/doc.go
  pkg/apis/kuma/v1alpha1/register.go
  pkg/apis/kuma/v1alpha1/trafficroute.go
  pkg/apis/kuma/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/kuma/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/kuma/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/kuma/v1alpha1/fake/fake_kuma_client.go
  pkg/client/clientset/versioned/typed/kuma/v1alpha1/fake/fake_trafficroute.go
  pkg/client/clientset/versioned/typed/kuma/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/kuma/v1alpha1/kuma_client.go
  pkg/client/clientset/versioned/typed/kuma/v1alpha1/trafficroute.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/kuma/interface.go
  pkg/client/informers/externalversions/kuma/v1alpha1/interface.go
  pkg/client/informers/externalversions/kuma/v1alpha1/trafficroute.go
  pkg/client/listers/kuma/v1alpha1/expansion_generated.go
  pkg/client/listers/kuma/v1alpha1/trafficroute.go
  pkg/metrics/observers/factory.go
  pkg/metrics/observers/kuma.go
  pkg/metrics/observers/kuma_test.go
  pkg/router/factory.go
  pkg/router/kuma.go
  pkg/router/kuma_test.go
  test/kuma/install.sh
  test/kuma/run.sh
  test/kuma/test-canary.sh
  test/workloads/init.sh
Labels: kind/feature

#1041 Add cluster name to flagger cmd args for altering
  cmd/flagger/main.go
  pkg/controller/controller.go
  pkg/controller/events.go
Labels: kind/enhancement

#1093 Fix failing kuma e2e tests
  kustomize/base/prometheus/deployment.yaml
  test/kuma/install.sh
  test/kuma/kustomization.yaml
  test/kuma/patch.yml
  test/kuma/prometheus.yml
Labels: kind/build

#1094 Publish a Software Bill of Materials (SBOM)
  .github/workflows/build.yaml
  .github/workflows/e2e.yaml
  .github/workflows/helm.yaml
  .github/workflows/push-ld.yml
  .github/workflows/release.yml
  .github/workflows/scan.yml
  .goreleaser.yml
Labels: kind/build
