Repository fluxcd/flagger, pull requests merged in 2022-05, with the labels that each got.

#1181 Add flag to disable cross namespace refs to Custom Resources
  charts/flagger/README.md
  charts/flagger/templates/deployment.yaml
  charts/flagger/values.yaml
  cmd/flagger/main.go
  docs/gitbook/faq.md
  pkg/apis/flagger/v1beta1/canary.go
  pkg/apis/flagger/v1beta1/zz_generated.deepcopy.go
  pkg/canary/daemonset_fixture_test.go
  pkg/canary/deployment_fixture_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/events.go
  pkg/controller/scheduler_daemonset_fixture_test.go
  pkg/controller/scheduler_deployment_fixture_test.go
  pkg/controller/scheduler_metrics.go
  pkg/controller/scheduler_svc_test.go
  pkg/router/gateway_api.go
  pkg/router/router_test.go
Labels: kind/enhancement

#1187 Update Flagger overview diagram
  README.md
  docs/diagrams/flagger-overview.png
Labels: kind/docs

#1208 Update Kubernetes packages to v1.24.1
  Makefile
  artifacts/flagger/account.yaml
  charts/flagger/templates/rbac.yaml
  cmd/flagger/main.go
  go.mod
  go.sum
  kustomize/base/flagger/rbac.yaml
  pkg/client/clientset/versioned/clientset.go
  pkg/loadtester/task_ngrinder_test.go
Labels: area/security
