Repository fluxcd/flagger, pull requests merged in 2023-01, with the labels that each got.

#1343 Support for overriding primary scaler replicas
  artifacts/flagger/crd.yaml
  charts/flagger/crds/crd.yaml
  docs/gitbook/tutorials/keda-scaledobject.md
  docs/gitbook/usage/how-it-works.md
  go.sum
  kustomize/base/flagger/crd.yaml
  pkg/apis/flagger/v1beta1/canary.go
  pkg/apis/flagger/v1beta1/zz_generated.deepcopy.go
  pkg/canary/hpa_reconciler.go
  pkg/canary/hpa_reconciler_test.go
  pkg/canary/scaled_object_reconciler.go
  pkg/canary/scaled_object_reconciler_test.go
Labels: kind/enhancement

#1352 Update Kubernetes packages to v1.26.1
  go.mod
  go.sum
  pkg/client/clientset/versioned/clientset.go
  pkg/client/informers/externalversions/factory.go
Labels: dependencies

#1356 build: Enable SBOM and SLSA Provenance
  .github/workflows/e2e.yaml
  .github/workflows/push-ld.yml
  .github/workflows/release.yml
Labels: kind/build
