Repository fluxcd/flagger, pull requests merged in 2024-03, with the labels that each got.

#1610 Fix link to alerting docs in changelog
  CHANGELOG.md
Labels: kind/docs

#1614 Updates google.golang.org/protobuf to v1.33.0
  go.mod
  go.sum
Labels: dependencies

#1622 Update dependencies (Go 1.22)
  .github/workflows/build.yaml
  .github/workflows/scan.yml
  Dockerfile
  Dockerfile.loadtester
  Makefile
  go.mod
  go.sum
Labels: dependencies

#1624 Setup Go toolchain for release workflow
  .github/workflows/release.yml
Labels: area/ci
