Repository fluxcd/flagger, pull requests merged in 2024-02, with the labels that each got.

#1564 Istio Canary TCP service support
  Makefile
  docs/gitbook/tutorials/istio-progressive-delivery.md
  pkg/apis/istio/v1alpha3/virtual_service.go
  pkg/apis/istio/v1alpha3/zz_generated.deepcopy.go
  pkg/router/istio.go
  pkg/router/istio_test.go
Labels: kind/feature

#1594 Build with Go 1.21 and Alpine 3.19
  .github/workflows/build.yaml
  Dockerfile
  Dockerfile.loadtester
  Makefile
  go.mod
  go.sum
Labels: dependencies

#1595 Update dependencies
  go.mod
  go.sum
Labels: dependencies, go

#1597 Fix Istio link in changelog
  CHANGELOG.md
Labels: kind/docs

#1599 Fix broken link in readme
  README.md
Labels: kind/docs
